### ISSUE TITLE
how to configure gatekeeper?

### ISSUE THREAD

**Issue by bwahn** [Xorlev/gatekeeper#14]
In AWS instance : Ubuntu 14.03

$ cd 
$ pwd
/home/ubuntu

$ sudo apt-get update
$ sudo apt-get install nginx
$ sudo apt-get install sudo apt-get install openjdk-7-jdk
$ sudo apt-get install maven2

$ cd /usr/local
$ wget http://apache.tt.co.kr/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
$ tar zxvf zookeeper-3.4.6.tar.gz
$ cd zookeeper-3.4.6/
$ cp conf/zoo_sample.cfg conf/zoo.cfg

$ vi conf/zoo.cfg
tickTime=2000
initLimit=10
syncLimit=5
dataDir=/tmp/zookeeper
clientPort=2181
server.1=localhost:2888:3888
maxClientCnxns=100

$ sudo mkdir /tmp/zookeeper
$ bin/zkServer.sh start

$ cd
$ git clone https://github.com/Xorlev/gatekeeper.git
$ cd gatekeeper/
$ mvn package
$ cp gatekeeper.properties.default /etc/nginx/gatekeeper.properties

$ vi /etc/nginx/gatekeeper.properties  // cluster_provider => discovery.impl
..
discovery.impl=com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery
..

$ cp nginx.conf.mustache.default /etc/nginx/nginx.conf

$ cp ./gatekeeper-agent/target/gatekeeper-agent-1.1.0-SNAPSHOT.jar /etc/nginx/

$ cd /etc/nginx
$ java -jar gatekeeper-agent-1.1.0-SNAPSHOT.jar /etc/nginx/gatekeeper.properties
07:22:12.877 [main] INFO  com.xorlev.gatekeeper.AppConfig - Initializing config with file=[gatekeeper.properties]
07:22:12.963 [main] WARN  c.n.c.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
07:22:12.964 [main] INFO  c.n.c.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
07:22:14.141 [main] INFO  c.n.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@379a935e
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) Error in custom provider, java.io.FileNotFoundException: nginx.conf.mustache (No such file or directory)
  at com.xorlev.gatekeeper.GatekeeperModule.providesNginxConfigWriter(GatekeeperModule.java:74)
  at com.xorlev.gatekeeper.GatekeeperModule.providesNginxConfigWriter(GatekeeperModule.java:74)
  while locating com.xorlev.gatekeeper.nginx.NginxConfigWriter
  at com.xorlev.gatekeeper.GatekeeperModule.configure(GatekeeperModule.java:42)
  while locating com.xorlev.gatekeeper.handler.ConfigWriter

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.xorlev.gatekeeper.GatekeeperApplication.<init>(GatekeeperApplication.java:31)
	at com.xorlev.gatekeeper.GatekeeperApplication.main(GatekeeperApplication.java:65)
Caused by: java.io.FileNotFoundException: nginx.conf.mustache (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.xorlev.gatekeeper.nginx.NginxConfigWriter.<init>(NginxConfigWriter.java:29)
	at com.xorlev.gatekeeper.GatekeeperModule.providesNginxConfigWriter(GatekeeperModule.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:105)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 6 more

And)

$ sudo service nginx restart
 * Restarting nginx nginx [failed]
==> It may be /etc/nginx/nginx.conf <=== nginx.conf.default ( gatekeeper) 

$ tail -f /var/log/nginx/error.log

2015/02/06 07:20:22 [emerg] 1035#0: unexpected "{" in /etc/nginx/nginx.conf:6

**Comment by Xorlev** [comment]
`nginx.conf.mustache.default` should be in the directory with Gatekeeper as `nginx.conf.mustache`. It will then use this file to write /etc/nginx/nginx.conf (as long as that's where you've configured your nginx config to be with the `nginx.config-file` in `gatekeeper.properties`

**Comment by bwahn** [comment]
I fixed nginx.conf.mustache as you said but I got another message as below,

Do you have idea?

$ vi /usr/local/zookeeper/conf/zoo.cfg

...
...
server.1=zookeeper.my.com:2888:3888
...

$ vi gatekeeper.properties
...
zookeeper.quorum=zookeeper.my.com
...

ubuntu@ip-172-31-6-191:/etc/nginx$ java -jar gatekeeper-agent-1.1.0-SNAPSHOT.jar /etc/nginx/gatekeeper.properties
14:45:47.596 [main] INFO  com.xorlev.gatekeeper.AppConfig - Initializing config with file=[gatekeeper.properties]
14:45:47.623 [main] WARN  c.n.c.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
14:45:47.623 [main] INFO  c.n.c.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
14:45:47.863 [main] INFO  c.n.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@379a935e
14:45:48.197 [ZookeeperClusterDiscovery STARTING] INFO  c.x.g.d.ZookeeperClusterDiscovery - Starting Zookeeper with connectString=zookeeper.my.com
14:45:48.202 [ZookeeperClusterDiscovery STARTING] WARN  c.n.c.retry.ExponentialBackoffRetry - maxRetries too large (100). Pinning to 29
14:45:48.231 [ZookeeperClusterDiscovery STARTING] INFO  c.n.c.f.imps.CuratorFrameworkImpl - Starting
14:45:48.232 [ZookeeperClusterDiscovery STARTING] DEBUG c.n.curator.CuratorZookeeperClient - Starting
14:45:48.232 [ZookeeperClusterDiscovery STARTING] DEBUG com.netflix.curator.ConnectionState - Starting
14:45:48.232 [ZookeeperClusterDiscovery STARTING] DEBUG com.netflix.curator.ConnectionState - reset
14:45:50.421 [ZookeeperClusterDiscovery STARTING] ERROR com.netflix.curator.ConnectionState - Connection timed out for connection string (zookeeper.my.com) and timeout (2000) / elapsed (2181)
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at com.netflix.curator.ConnectionState.getZooKeeper(ConnectionState.java:101) ~[gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:107) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.utils.EnsurePath$InitialHelper$1.call(EnsurePath.java:128) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.RetryLoop.callWithRetry(RetryLoop.java:106) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.utils.EnsurePath$InitialHelper.ensure(EnsurePath.java:120) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.utils.EnsurePath.ensure(EnsurePath.java:90) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:72) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.imps.NamespaceImpl.newNamespaceAwareEnsurePath(NamespaceImpl.java:85) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.imps.CuratorFrameworkImpl.newNamespaceAwareEnsurePath(CuratorFrameworkImpl.java:428) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.recipes.cache.PathChildrenCache.<init>(PathChildrenCache.java:198) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.recipes.cache.PathChildrenCache.<init>(PathChildrenCache.java:169) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.x.discovery.details.ServiceCacheImpl.<init>(ServiceCacheImpl.java:60) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.x.discovery.details.ServiceCacheBuilderImpl.build(ServiceCacheBuilderImpl.java:47) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.initializeServiceCaches(ZookeeperClusterDiscovery.java:93) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.setupServiceDiscovery(ZookeeperClusterDiscovery.java:76) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.startUp(ZookeeperClusterDiscovery.java:39) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
14:45:50.425 [ZookeeperClusterDiscovery STARTING] DEBUG com.netflix.curator.RetryLoop - Retry-able exception received
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at com.netflix.curator.ConnectionState.getZooKeeper(ConnectionState.java:101) ~[gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:107) ~[gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.utils.EnsurePath$InitialHelper$1.call(EnsurePath.java:128) ~[gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.RetryLoop.callWithRetry(RetryLoop.java:106) ~[gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.utils.EnsurePath$InitialHelper.ensure(EnsurePath.java:120) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.utils.EnsurePath.ensure(EnsurePath.java:90) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.imps.NamespaceImpl.fixForNamespace(NamespaceImpl.java:72) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.imps.NamespaceImpl.newNamespaceAwareEnsurePath(NamespaceImpl.java:85) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.imps.CuratorFrameworkImpl.newNamespaceAwareEnsurePath(CuratorFrameworkImpl.java:428) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.recipes.cache.PathChildrenCache.<init>(PathChildrenCache.java:198) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.framework.recipes.cache.PathChildrenCache.<init>(PathChildrenCache.java:169) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.x.discovery.details.ServiceCacheImpl.<init>(ServiceCacheImpl.java:60) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.netflix.curator.x.discovery.details.ServiceCacheBuilderImpl.build(ServiceCacheBuilderImpl.java:47) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.initializeServiceCaches(ZookeeperClusterDiscovery.java:93) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.setupServiceDiscovery(ZookeeperClusterDiscovery.java:76) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.startUp(ZookeeperClusterDiscovery.java:39) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [gatekeeper-agent-1.1.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
14:45:50.526 [ZookeeperClusterDiscovery STARTING] DEBUG com.netflix.curator.RetryLoop - Retrying operation

**Comment by Xorlev** [comment]
I'll assume you don't own my.com. You'll need to configure gatekeeper to
point at your Zookeeper quorum.

**Comment by bwahn** [comment]
I updated

$ vi /usr/local/zookeeper/conf/zoo.cfg
..
server.1=172.31.6.191:2888:3888
...

$ vi gatekeeper.properties
...
zookeeper.quorum=172.31.6.191
...

and, 

ubuntu@:/etc/nginx$ java -jar gatekeeper-agent-1.1.0-SNAPSHOT.jar /etc/nginx/gatekeeper.properties
06:42:24.055 [main] INFO  com.xorlev.gatekeeper.AppConfig - Initializing config with file=[gatekeeper.properties]
06:42:24.082 [main] WARN  c.n.c.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
06:42:24.082 [main] INFO  c.n.c.sources.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
06:42:24.323 [main] INFO  c.n.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@379a935e
06:42:24.656 [ZookeeperClusterDiscovery STARTING] INFO  c.x.g.d.ZookeeperClusterDiscovery - Starting Zookeeper with connectString=172.31.6.191
06:42:24.660 [ZookeeperClusterDiscovery STARTING] WARN  c.n.c.retry.ExponentialBackoffRetry - maxRetries too large (100). Pinning to 29
06:42:24.689 [ZookeeperClusterDiscovery STARTING] INFO  c.n.c.f.imps.CuratorFrameworkImpl - Starting
06:42:24.690 [ZookeeperClusterDiscovery STARTING] DEBUG c.n.curator.CuratorZookeeperClient - Starting
06:42:24.690 [ZookeeperClusterDiscovery STARTING] DEBUG com.netflix.curator.ConnectionState - Starting
06:42:24.690 [ZookeeperClusterDiscovery STARTING] DEBUG com.netflix.curator.ConnectionState - reset
06:42:24.801 [ZookeeperClusterDiscovery STARTING-EventThread] INFO  c.n.c.f.state.ConnectionStateManager - State change: CONNECTED
06:42:24.802 [ConnectionStateManager-0] WARN  c.n.c.f.state.ConnectionStateManager - There are no ConnectionStateListeners registered.

did it rightly start?

**Comment by Xorlev** [comment]
That looks to me like it started correctly. Let me know if you need any more help. :)
