### ISSUE TITLE
Got JsonParseException: Unexpected character ('i' (code 105))

### ISSUE THREAD

**Issue by vmquan** [Xorlev/gatekeeper#23]
I create znode in zookeeper follow commands below:
```
create /discovery namespace
create /discovery/services thiscoveryPath
create /discovery/services/service-a cluster-a
create /discovery/services/service-b cluster-b
create /discovery/services/service-a/instance-1 instance-1
create /discovery/services/service-a/instance-2 instance-2
create /discovery/services/service-b/instance-1 instance-1
```
my  gatekeeper.properties
```
# Cluster provider impl to use
discovery.impl=com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery

################################################
# Only applicable for ZookeeperClusterProvider #
################################################
zookeeper.quorum=localhost # standalone mode.
zookeeper.namespace=discovery
zookeeper.discoveryPath=/services
....
```

I got exeption when execute `java -jar...`
```
SEVERE: Service ZookeeperClusterDiscovery [FAILED] has failed in the STARTING state.
org.codehaus.jackson.JsonParseException: Unexpected character ('i' (code 105)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@729acbd; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
	at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2090)
	at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:606)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:492)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1973)
	at com.netflix.curator.x.discovery.details.JsonInstanceSerializer.deserialize(JsonInstanceSerializer.java:50)
	at com.netflix.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:175)
	at com.netflix.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:78)
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.initializeServiceCaches(ZookeeperClusterDiscovery.java:106)
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.setupServiceDiscovery(ZookeeperClusterDiscovery.java:76)
	at com.xorlev.gatekeeper.discovery.ZookeeperClusterDiscovery.startUp(ZookeeperClusterDiscovery.java:39)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:745)
```

What's wrong in my steps? Could you take a look.

**Comment by Xorlev** [comment]
The examples I provided aren't intended to be used as raw znode creation commands. This service is intended to be used with the Apache Curator service discovery library. It generates a JSON blob with metadata about the instance.

Please see http://curator.apache.org/curator-x-discovery/index.html for more information. For reference, it's a serialized `ServiceInstance` object which is written as the znode payload.

I'll make this more clear in the README. Sorry about that!
